<?php

class mod_eppctwo_prospects extends rs_object{
	public static $db, $cols, $primary_key;

	public static function set_table_definition(){
		self::$db = 'eppctwo';
		self::$primary_key = array('id');
		self::$uniques = array(array(;''));

		self::$cols = self::init_cols(
			new rs_col('id'                         ,'bigint'                ,20    ,''		),
			new rs_col('client_id'                  ,'char'                  ,16    ,''		),
			new rs_col('parent_id'                  ,'bigint'                ,20    ,''		),
			new rs_col('company'                    ,'int'                   ,11    ,''		),
			new rs_col('user'                       ,'int'                   ,11    ,''		),
			new rs_col('create_date'                ,'date'                  ,''    ,''		),
			new rs_col('mod_date'                   ,'date'                  ,''    ,''		),
			new rs_col('close_date'                 ,'date'                  ,''    ,''		),
			new rs_col('url_key'                    ,'varchar'               ,128   ,''		),
			new rs_col('status'                     ,'varchar'               ,32    ,''		),
			new rs_col('name'                       ,'varchar'               ,128   ,''		),
			new rs_col('prospect_company'           ,'varchar'               ,128   ,''		),
			new rs_col('title'                      ,'varchar'               ,128   ,''		),
			new rs_col('address'                    ,'varchar'               ,128   ,''		),
			new rs_col('city'                       ,'varchar'               ,64    ,''		),
			new rs_col('state'                      ,'varchar'               ,2     ,''		),
			new rs_col('country'                    ,'varchar'               ,64    ,''		),
			new rs_col('zip'                        ,'varchar'               ,8     ,''		),
			new rs_col('url'                        ,'varchar'               ,128   ,''		),
			new rs_col('email'                      ,'varchar'               ,128   ,''		),
			new rs_col('phone'                      ,'varchar'               ,32    ,''		),
			new rs_col('fax'                        ,'varchar'               ,32    ,''		),
			new rs_col('revenue'                    ,'float'                 ,7,2   ,''		),
			new rs_col('ppc_package'                ,'int'                   ,11    ,''		),
			new rs_col('ppc_budget'                 ,'double'                ,''    ,''		),
			new rs_col('ppc_mgmt_perc'              ,'int'                   ,2     ,''		),
			new rs_col('ppc_mgmt'                   ,'double'                ,''    ,''		),
			new rs_col('ppc_setup_fee'              ,'int'                   ,11    ,''		),
			new rs_col('ppc_contract_length'        ,'varchar'               ,64    ,''		),
			new rs_col('ppc_clicks'                 ,'tinyint'               ,4     ,''		),
			new rs_col('seo_package'                ,'int'                   ,11    ,''		),
			new rs_col('seo_package_amount'         ,'double'                ,''    ,''		),
			new rs_col('seo_blog'                   ,'tinyint'               ,4     ,''		),
			new rs_col('seo_blog_amount'            ,'double'                ,''    ,''		),
			new rs_col('seo_blog_mgmt'              ,'tinyint'               ,4     ,''		),
			new rs_col('seo_blog_mgmt_amount'       ,'double'                ,''    ,''		),
			new rs_col('seo_monthly_amount'         ,'double'                ,''    ,''		),
			new rs_col('seo_amount'                 ,'double'                ,''    ,''		),
			new rs_col('smo_package'                ,'int'                   ,11    ,''		),
			new rs_col('smo_amount'                 ,'double'                ,''    ,''		),
			new rs_col('infographic'                ,'tinyint'               ,1     ,''		),
			new rs_col('ig_num'                     ,'int'                   ,2     ,''		),
			new rs_col('seo_ig_amount'              ,'int'                   ,11    ,''		),
			new rs_col('seo_ig_discount'            ,'int'                   ,11    ,''		),
			new rs_col('wd_package'                 ,'int'                   ,11    ,''		),
			new rs_col('wd_op'                      ,'tinyint'               ,4     ,''		),
			new rs_col('wd_landing_page'            ,'tinyint'               ,4     ,''		),
			new rs_col('wd_landing_page_testing'    ,'tinyint'               ,4     ,''		),
			new rs_col('wd_num_landing_pages'       ,'smallint'              ,6     ,''		),
			new rs_col('wd_deliverables'            ,'varchar'               ,512   ,''		),
			new rs_col('wd_amount'                  ,'double'                ,''    ,''		),
			new rs_col('wd_pay_half'                ,'tinyint'               ,4     ,''		),
			new rs_col('wd_first_month_amount'      ,'double'                ,''    ,''		),
			new rs_col('signature'                  ,'varchar'               ,128   ,''		),
			new rs_col('sig_title'                  ,'varchar'               ,50    ,''		),
			new rs_col('sig_month'                  ,'varchar'               ,2     ,''		),
			new rs_col('sig_day'                    ,'varchar'               ,2     ,''		),
			new rs_col('sig_year'                   ,'varchar'               ,4     ,''		),
			new rs_col('ip'                         ,'varchar'               ,25    ,''		),
			new rs_col('payment_method'             ,'varchar'               ,16    ,''		),
			new rs_col('ppc_discount'               ,'int'                   ,11    ,''		),
			new rs_col('seo_discount'               ,'int'                   ,11    ,''		),
			new rs_col('smo_discount'               ,'int'                   ,11    ,''		),
			new rs_col('wd_discount'                ,'int'                   ,11    ,''		),
			new rs_col('test'                       ,'int'                   ,11    ,''		),
			new rs_col('test1'                      ,'int'                   ,11    ,''		),
			new rs_col('test2'                      ,'int'                   ,11    ,''		),
			new rs_col('fba_package'                ,'tinyint'               ,1     ,''		),
			new rs_col('fba_budget'                 ,'double'                ,''    ,''		),
			new rs_col('fba_mgmt_perc'              ,'int'                   ,2     ,''		),
			new rs_col('fba_mgmt'                   ,'double'                ,''    ,''		),
			new rs_col('fba_setup_fee'              ,'int'                   ,11    ,''		),
			new rs_col('fba_discount'               ,'int'                   ,11    ,''		),
			new rs_col('fba_clicks'                 ,'tinyint'               ,1     ,''		),
			new rs_col('slb_package'                ,'int'                   ,11    ,''		),
			new rs_col('slb_amount'                 ,'double'                ,''    ,''		),
			new rs_col('slb_discount'               ,'int'                   ,11    ,''		),
			new rs_col('ql_pro_package'             ,'int'                   ,1     ,''		),
			new rs_col('ql_pro_budget'              ,'double'                ,''    ,''		),
			new rs_col('ql_pro_mgmt_fee'            ,'double'                ,''    ,''		),
			new rs_col('ql_pro_setup_fee'           ,'double'                ,''    ,''		),
			new rs_col('ql_pro_ct_fee'              ,'double'                ,''    ,''		),
			new rs_col('gs_pro_package'             ,'int'                   ,1     ,''		),
			new rs_col('gs_pro_hours'               ,'double'                ,''    ,''		),
			new rs_col('gs_pro_mgmt_fee'            ,'double'                ,''    ,''		),
			new rs_col('gs_pro_setup_fee'           ,'double'                ,''    ,''		)
			);
	}
}
?>
