<?php
namespace phpadcenter\services\Reporting;

class ReportingEnum
{
	public static $AccountPerformanceReportColumn          = array('AccountName','AccountNumber','TimePeriod','CurrencyCode','AdDistribution','Impressions','Clicks','Ctr','AverageCpc','Spend','AveragePosition','Conversions','ConversionRate','CostPerConversion','LowQualityClicks','LowQualityClicksPercent','LowQualityImpressions','LowQualityImpressionsPercent','LowQualityConversions','LowQualityConversionRate','AverageCpm','DeviceType','DeviceOS','ImpressionSharePercent','ImpressionLostToBudgetPercent','ImpressionLostToRankPercent','ImpressionLostToRelevancePercent','ImpressionLostToOthersPercent','ImpressionLostToBidPercent','ImpressionLostToLandingPageRelevancePercent','ImpressionLostToKeywordRelevancePercent');
	public static $AdDistributionReportFilter              = array('Search','Content');
	public static $AdDynamicTextPerformanceReportColumn    = array('AccountName','AccountNumber','TimePeriod','LanguageAndRegion','AdGroupName','AdGroupId','Keyword','AdId','AdTitle','AdType','DestinationUrl','Param1','Param2','Param3','CurrencyCode','AdDistribution','Impressions','Clicks','Ctr','AverageCpc','Spend','AveragePosition','Conversions','ConversionRate','CostPerConversion','AverageCpm','PricingModel','DeviceType','Language');
	public static $AdExtensionByAdExtensionItemColumn      = array('AccountName','TimePeriod','CampaignName','CampaignId','AdGroupName','AdGroupId','AdTitle','AdId','AdExtensionTypeName','AdExtensionTypeId','AdExtensionId','AdExtensionVersion','AdExtensionPropertyValue','Impressions','DeviceType','DeviceOS','Clicks','Ctr','Conversions','CostPerConversion','ConversionRate');
	public static $AdExtensionByAdsReportColumn            = array('AccountName','TimePeriod','CampaignName','CampaignId','AdGroupName','AdGroupId','AdTitle','AdId','AdExtensionType','DeviceType','DeviceOS','Impressions','Clicks','TotalClicks','Conversions','Ctr','AverageCpc','ConversionRate','Spend','AdExtensionId','AdExtensionVersion','AccountNumber','AccountId','ClickType');
	public static $AdExtensionByKeywordReportColumn        = array('AccountName','TimePeriod','CampaignName','CampaignId','AdGroupName','AdGroupId','Keyword','KeywordId','AdExtensionType','DeviceType','DeviceOS','Impressions','Clicks','TotalClicks','Conversions','Ctr','AverageCpc','ConversionRate','Spend','AdExtensionId','AdExtensionVersion','AccountNumber','AccountId','ClickType');
	public static $AdExtensionDimensionReportColumn        = array('AccountId','AdExtensionType','AdExtensionId','AdExtensionVersion','Status','AdExtensionPropertyId','AdExtensionPropertyValue');
	public static $AdGroupPerformanceReportColumn          = array('AccountName','AccountNumber','TimePeriod','LanguageAndRegion','Status','CampaignName','CampaignId','AdGroupName','AdGroupId','CurrencyCode','AdDistribution','Impressions','Clicks','Ctr','AverageCpc','Spend','AveragePosition','Conversions','ConversionRate','CostPerConversion','AverageCpm','PricingModel','DeviceType','Language','DeviceOS','ImpressionSharePercent','ImpressionLostToBudgetPercent','ImpressionLostToRankPercent','ImpressionLostToRelevancePercent','ImpressionLostToOthersPercent','QualityScore','KeywordRelevance','LandingPageRelevance','LandingPageUserExperience','HistoricQualityScore','HistoricKeywordRelevance','HistoricLandingPageRelevance','HistoricLandingPageUserExperience','ImpressionLostToBidPercent','ImpressionLostToLandingPageRelevancePercent','ImpressionLostToKeywordRelevancePercent','BusinessListingId','BusinessListingName','BusinessCategoryId','BusinessCategoryName');
	public static $AdGroupStatusReportFilter               = array('Submitted','Deleted','Expired','Draft','Paused','Active');
	public static $AdPerformanceReportColumn               = array('AccountName','AccountNumber','TimePeriod','LanguageAndRegion','CampaignName','AdGroupName','AdId','AdGroupId','AdTitle','AdDescription','AdType','CurrencyCode','AdDistribution','Impressions','Clicks','Ctr','AverageCpc','Spend','AveragePosition','Conversions','ConversionRate','CostPerConversion','AverageCpm','PricingModel','DestinationUrl','DeviceType','Language','DisplayUrl','BusinessListingId','BusinessListingName','BusinessCategoryId','BusinessCategoryName');
	public static $AdStatusReportFilter                    = array('Submitted','Rejected','Deleted','Pending','Active');
	public static $AdTypeReportFilter                      = array('Text','Mobile','Image','RichMedia','Local','ThirdPartyCreative','RichAd');
	public static $AgeGenderDemographicReportColumn        = array('AccountName','AccountNumber','TimePeriod','LanguageAndRegion','CampaignName','AdGroupName','AdDistribution','AgeGroup','Gender','EstimatedImpressionPercent','EstimatedClickPercent','EstimatedCtr','Language');
	public static $AgeGroupReportFilter                    = array('Unknown','Ages0to12','Ages13to17','Ages18to24','Ages25to34','Ages35to49','Ages50to64','Ages65plus');
	public static $BehavioralPerformanceReportColumn       = array('AccountName','AccountNumber','AccountId','TimePeriod','LanguageAndRegion','CampaignName','CampaignId','AdGroupName','AdGroupId','BehavioralId','BehavioralName','AdId','DestinationUrl','CurrentMaxCpc','CurrencyCode','MatchType','AdDistribution','Impressions','Clicks','Ctr','AverageCpc','Spend','AveragePosition','Conversions','ConversionRate','CostPerConversion','AdType','AverageCpm','PricingModel');
	public static $BehavioralTargetReportColumn            = array('AccountName','AccountNumber','AccountId','TimePeriod','CurrencyCode','CampaignId','CampaignName','LanguageAndRegion','BehavioralId','AdGroupId','AdGroupName','AdDistribution','Impressions','Clicks','Ctr','AverageCpc','Spend','AveragePosition','AverageCpm','PricingModel');
	public static $BidMatchTypeReportFilter                = array('Exact','Phrase','Broad','Content');
	public static $BudgetSummaryReportColumn               = array('AccountName','AccountNumber','CampaignName','Date','CurrencyCode','MonthlyBudget','DailySpend','MonthToDateSpend');
	public static $BudgetSummaryReportTimePeriod           = array('Today','Yesterday','LastSevenDays','ThisMonth','LastMonth');
	public static $CampaignPerformanceReportColumn         = array('AccountName','AccountNumber','TimePeriod','Status','CampaignName','CampaignId','CurrencyCode','AdDistribution','Impressions','Clicks','Ctr','AverageCpc','Spend','AveragePosition','Conversions','ConversionRate','CostPerConversion','LowQualityClicks','LowQualityClicksPercent','LowQualityImpressions','LowQualityImpressionsPercent','LowQualityConversions','LowQualityConversionRate','AverageCpm','DeviceType','DeviceOS','ImpressionSharePercent','ImpressionLostToBudgetPercent','ImpressionLostToRankPercent','ImpressionLostToRelevancePercent','ImpressionLostToOthersPercent','QualityScore','KeywordRelevance','LandingPageRelevance','LandingPageUserExperience','HistoricQualityScore','HistoricKeywordRelevance','HistoricLandingPageRelevance','HistoricLandingPageUserExperience','ImpressionLostToBidPercent','ImpressionLostToLandingPageRelevancePercent','ImpressionLostToKeywordRelevancePercent');
	public static $CampaignStatusReportFilter              = array('Submitted','Cancelled','Deleted','Paused','BudgetPaused','Active');
	public static $CashbackReportFilter                    = array('NotEnabled','Enabled');
	public static $ChangeEntityReportFilter                = array('Account','Campaign','AdGroup','Ad','Keyword');
	public static $ChangeTypeReportFilter                  = array('Added','Deleted','Changed');
	public static $ComponentTypeFilter                     = array('Basic','Deeplink','Form','Image','FavoriteIcon','Video','TitledLink');
	public static $ConversionPerformanceReportColumn       = array('AccountName','AccountNumber','AccountId','TimePeriod','CampaignName','CampaignId','AdGroupName','AdGroupId','Keyword','KeywordId','Impressions','Clicks','Ctr','Assists','Conversions','ConversionRate','Spend','ExtendedCost','Revenue','ReturnOnAdSpend','CostPerConversion','CostPerAssist','RevenuePerConversion','RevenuePerAssist','DeviceType');
	public static $CountryReportFilter                     = array('Canada','France','Singapore','UnitedKingdom','UnitedStates');
	public static $DeliveredMatchTypeReportFilter          = array('Exact','Phrase','Broad','Content');
	public static $DestinationUrlPerformanceReportColumn   = array('AccountName','AccountNumber','TimePeriod','LanguageAndRegion','CampaignName','CampaignId','AdGroupName','AdGroupId','AdId','CurrencyCode','AdDistribution','DestinationUrl','Impressions','Clicks','Ctr','AverageCpc','Spend','AveragePosition','Conversions','ConversionRate','CostPerConversion','AverageCpm','PricingModel','DeviceType','Language');
	public static $DeviceTypeReportFilter                  = array('Computer','SmartPhone','NonSmartPhone','Tablet');
	public static $GenderReportFilter                      = array('Unknown','Male','Female');
	public static $GoalsAndFunnelsReportColumn             = array('AccountName','AccountNumber','AccountId','TimePeriod','CampaignName','CampaignId','AdGroupName','AdGroupId','Keyword','KeywordId','Goal','Step1Count','Step2Count','Step3Count','Step4Count','Step5Count','Conversions','Assists','FunnelConversionRate','Spend','Revenue','ReturnOnAdSpend','ExtendedCost');
	public static $KeywordMigrationReportColumn            = array('AccountName','AccountId','CampaignName','CampaignId','AdGroupName','AdGroupId','Keyword','KeywordId','PreviousKeywordId','BidMatchType');
	public static $KeywordPerformanceReportColumn          = array('AccountName','AccountNumber','AccountId','TimePeriod','LanguageAndRegion','CampaignName','CampaignId','AdGroupName','AdGroupId','Keyword','KeywordId','AdId','AdType','DestinationUrl','CurrentMaxCpc','CurrencyCode','MatchType','AdDistribution','Impressions','Clicks','Ctr','AverageCpc','Spend','AveragePosition','Conversions','ConversionRate','CostPerConversion','AverageCpm','PricingModel','Cashback','BidMatchType','DeviceType','QualityScore','KeywordRelevance','LandingPageRelevance','LandingPageUserExperience','Language','HistoricQualityScore','HistoricKeywordRelevance','HistoricLandingPageRelevance','HistoricLandingPageUserExperience','KeywordMatchTypeId','QualityImpact','BusinessListingId','BusinessListingName','BusinessCategoryId','BusinessCategoryName');
	public static $LanguageAndRegionReportFilter           = array('EnglishCanada','FrenchCanada','France','Singapore','UnitedKingdom','UnitedStates');
	public static $MetroAreaDemographicReportColumn        = array('AccountName','AccountNumber','TimePeriod','LanguageAndRegion','CampaignName','AdGroupName','Country','State','MetroArea','CurrencyCode','AdDistribution','Impressions','Clicks','Ctr','AverageCpc','Spend','AveragePosition','AverageCpm','ProximityTargetLocation','Radius','Language','City','QueryIntentCountry','QueryIntentState','QueryIntentCity','QueryIntentDMA');
	public static $NegativeKeywordConflictReportColumn     = array('AccountName','AccountNumber','AccountId','CampaignName','CampaignId','AdGroupName','AdGroupId','Keyword','KeywordId','NegativeKeyword','ConflictLevel');
	public static $NonHourlyReportAggregation              = array('Summary','Daily','Weekly','Monthly','Yearly');
	public static $PublisherUsagePerformanceReportColumn   = array('AccountName','AccountNumber','AccountId','TimePeriod','LanguageAndRegion','CampaignName','CampaignId','AdGroupName','AdGroupId','CurrencyCode','AdDistribution','PublisherUrl','Impressions','Clicks','Ctr','AverageCpc','Spend','AveragePosition','Conversions','ConversionRate','CostPerConversion','AverageCpm','PricingModel','Language');
	public static $ReportAggregation                       = array('Summary','Hourly','Daily','Weekly','Monthly','Yearly','HourOfDay','DayOfWeek');
	public static $ReportFormat                            = array('Csv','Tsv','Xml');
	public static $ReportLanguage                          = array('English','French');
	public static $ReportRequestStatusType                 = array('Error','Success','Pending');
	public static $ReportTimePeriod                        = array('Today','Yesterday','LastSevenDays','ThisWeek','LastWeek','LastFourWeeks','ThisMonth','LastMonth','LastThreeMonths','LastSixMonths','ThisYear','LastYear');
	public static $RichAdComponentPerformanceReportColumn  = array('AccountName','AccountNumber','TimePeriod','AdId','AdTitle','CampaignName','AdGroupName','AdGroupId','RichAdSubType','ComponentType','ComponentTitle','ComponentDestinationURL','ComponentPosition','ComponentClicks','ComponentNonBillableClicks','ComponentTotalClicks','ComponentCTR');
	public static $RichAdSubTypeFilter                     = array('Rais2Images4Links','Rais2Images2Links1Form','RaisPharma','Rais1Video4Links','Rais1Video2Links1Form');
	public static $SearchCampaignChangeHistoryReportColumn = array('DateTime','ChangedBy','CampaignName','AdGroupName','AdTitle','AdDescription','DisplayUrl','Keyword','ItemChanged','AttributeChanged','HowChanged','OldValue','NewValue');
	public static $SearchQueryPerformanceReportColumn      = array('AccountName','AccountNumber','AccountId','TimePeriod','CampaignName','CampaignId','AdGroupName','AdGroupId','AdId','AdType','DestinationUrl','MatchType','LanguageAndRegion','CampaignStatus','AdStatus','Impressions','Clicks','Ctr','AverageCpc','Spend','AveragePosition','SearchQuery','Keyword','Conversions','ConversionRate','CostPerConversion','Language','KeywordId');
	public static $SearchQueryReportAggregation            = array('Summary','Hourly','Daily','Weekly','Monthly');
	public static $SegmentationReportColumn                = array('AccountName','AccountNumber','AccountId','TimePeriod','CampaignName','CampaignId','AdGroupName','AdGroupId','Keyword','KeywordId','Goal','AgeGroup','Gender','Country','State','MetroArea','Step1Count','Step2Count','Step3Count','Step4Count','Step5Count','Conversions','Assists','Spend','FunnelConversionRate','Revenue','ReturnOnAdSpend');
	public static $ShareOfVoiceReportColumn                = array('AccountName','TimePeriod','ProductName','CampaignName','AdGroupName','LanguageAndRegion','Keyword','MatchType','BidMatchType','Language','AccountNumber','AccountId','KeywordId','AdGroupId','CampaignId','Impressions','Clicks','Ctr','AverageCpc','Spend','AveragePosition','ImpressionSharePercent','ImpressionLostToBudgetPercent','ImpressionLostToRankPercent','ImpressionLostToLandingPageRelevancePercent','ImpressionLostToKeywordRelevancePercent','ImpressionLostToRelevancePercent','ImpressionLostToBidPercent','CurrentMaxCpc','QualityScore','KeywordRelevance','LandingPageRelevance','LandingPageUserExperience','Conversions','ConversionRate','CostPerConversion','AdDistribution','ClickSharePercent');
	public static $SitePerformanceReportColumn             = array('AccountName','AccountNumber','AccountId','TimePeriod','LanguageAndRegion','CampaignName','CampaignId','AdGroupName','AdGroupId','Site','SiteId','AdId','DestinationUrl','CurrentMaxCpc','CurrencyCode','MatchType','AdDistribution','Impressions','Clicks','Ctr','AverageCpc','Spend','AveragePosition','Conversions','ConversionRate','CostPerConversion','AdType','AverageCpm','PricingModel','DeviceType','Language');
	public static $TacticChannelReportColumn               = array('AccountName','AccountNumber','AccountId','TimePeriod','Tactic','Channel','ThirdPartyCampaign','ThirdPartyAdGroup','ThirdPartyTerm','CampaignName','CampaignId','AdGroupName','AdGroupId','Keyword','KeywordId','Goal','Step1Count','Step2Count','Step3Count','Step4Count','Step5Count','Conversions','Assists','Spend','FunnelConversionRate','Revenue','ReturnOnAdSpend');
	public static $TrafficSourcesReportColumn              = array('AccountName','AccountNumber','AccountId','TimePeriod','Source','Goal','Step1Count','Step2Count','Step3Count','Step4Count','Step5Count','Conversions','Assists','FunnelConversionRate','Revenue','RevenuePerConversion');

	/**
	 * typed args
	 */
	public static $ReportRequestType                       = array('AccountPerformanceReportRequest','AdDynamicTextPerformanceReportRequest','AdExtensionByAdsReportRequest','AdExtensionByKeywordReportRequest','AdExtensionDimensionReportRequest','AdGroupPerformanceReportRequest','AdPerformanceReportRequest','AgeGenderDemographicReportRequest','BehavioralPerformanceReportRequest','BehavioralTargetReportRequest','BudgetSummaryReportRequest','CampaignPerformanceReportRequest','ConversionPerformanceReportRequest','DestinationUrlPerformanceReportRequest','GoalsAndFunnelsReportRequest','KeywordMigrationReportRequest','KeywordPerformanceReportRequest','MetroAreaDemographicReportRequest','NegativeKeywordConflictReportRequest','PublisherUsagePerformanceReportRequest','RichAdComponentPerformanceReportRequest','SearchCampaignChangeHistoryReportRequest','SearchQueryPerformanceReportRequest','SegmentationReportRequest','ShareOfVoiceReportRequest','SitePerformanceReportRequest','TacticChannelReportRequest','TrafficSourcesReportRequest');
}

?>