<?php
namespace phpadcenter\services\CustomerManagement;

class CustomerManagementEnum
{
	public static $AccountFinancialStatus      = array('Proposed','PendingCreditCheck','ClearFinancialStatus','SoldToOnly','CreditWarning','Hold','WriteOff','TaxOnHold','UserHold');
	public static $AccountLifeCycleStatus      = array('Draft','Active','Inactive','Pause','Pending');
	public static $AccountType                 = array('Advertiser','Publisher');
	public static $ApplicationType             = array('Advertiser','Publisher');
	public static $CurrencyType                = array('AlgerianDinar','ArgentinePeso','ArmenianDram','AustralianDollar','AzerbaijanianManat','BahrainiDinar','Baht','Balboa','BelarussianRuble','BelizeDollar','Bolivar','Boliviano','BrazilianReal','BruneiDollar','CanadianDollar','ChileanPeso','ColombianPeso','CordobaOro','CostaRicanColon','Croatiankuna','CzechKoruna','DanishKrone','Denar','DominicanPeso','Dong','EgyptianPound','Euro','Forint','Guarani','HongKongDollar','Hryvnia','IcelandKrona','IndianRupee','IranianRial','IraqiDinar','JamaicanDollar','JapaneseYen','JordanianDinar','KenyanShilling','Kroon','KuwaitiDinar','Lari','LatvianLats','LebanesePound','Lek','Lempira','Leu','Lev','LibyanDinar','LithuanianLitus','MalaysianRinggit','MexicanPeso','MoroccanDirham','NewIsraeliSheqel','NewTaiwanDollar','NewZealandDollar','NorwegianKrone','NuevoSol','PakistanRupee','Pataca','PesoUruguayo','PhilippinePeso','QatariRial','Quetzal','RialOmani','Rufiyaa','Rupiah','RussianRuble','SaudiRiyal','SingaporeDollar','SlovakKoruna','Som','SouthAfricanRand','SwedishKrona','SwissFranc','SyrianPound','Tenge','Tolar','TrinidadandTobagoDollar','Tugrik','TunisianDinar','TurkishLira','UAEDirham','UKPound','USDollar','UzbekistanSum','Won','YemeniRial','YuanRenminbi','YugoslavianNewDinar','ZimbabweDollar','Zloty');
	public static $CustomerFinancialStatus     = array('ProposalsOnly','PendingCreditCheck','ClearFinancialStatus','SoldToOnly','CreditHold','CreditWarning');
	public static $CustomerLifeCycleStatus     = array('Active','Inactive');
	public static $EmailFormat                 = array('Html','Text');
	public static $Industry                    = array('NA','AgencySalesHouse','Automotive','ConsumerPackagedGoods','Education','Entertainment','FinancialServices','FoodServices','Gaming','GovernmentNonprofitPolitical','Healthcare','Internal','PublishingAndWebMedia','RealEstate','Retail','Services','Technology','Telecommunications','TravelHospitality','Other','Pharmaceuticals');
	public static $LCID                        = array('ArabicSaudiArabia','ChineseTaiwan','DanishDenmark','GermanGermany','EnglishUS','SpanishSpain','FinnishFinland','FrenchFrance','HebrewIsrael','ItalianItaly','KoreanKorea','DutchNetherlands','NorwegianNorway','PortuguesePortugal','RussianRussia','SwedishSweden','EnglishThailand','EnglishIndonesia','EnglishVietnam','GermanSwitzerland','EnglishUK','SpanishMexico','ChineseHongKong','GermanAustria','EnglishAustralia','FrenchCanada','EnglishCanada','EnglishNewZealand','EnglishIreland','SpanishVenezuela','SpanishColombia','SpanishPeru','SpanishArgentina','EnglishPhilippines','SpanishChile','EnglishIndia','EnglishMalaysia','EnglishSingapore');
	public static $LanguageType                = array('Danish','Dutch','English','Finnish','French','German','Italian','Japanese','Norwegian','Portuguese','Swedish','Spanish','Arabic','Hebrew','Korean','Russian','Chinese');
	public static $ManageAccountsRequestStatus = array('Accepted','Cancelled','Declined','Failed','Inactive','InProgress','Pending','Succeeded');
	public static $ManageAccountsRequestType   = array('EndedByAdvertiser','EndedByAgency','RequestedByAdvertiser','RequestedByAgency');
	public static $PaymentMethodType           = array('CreditCard','Invoice','Check','ElectronicFundsTransfer');
	public static $SecretQuestion              = array('None','FavoritePetsName','FavoriteMovie','Anniversary','FatherMiddleName','SpouseMiddleName','FirstChildMiddleName','HighSchoolName','FavoriteTeacherName','FavoriteSportsTeam');
	public static $ServiceLevel                = array('SelfServe','SelfServeTrusted','Premium','Internal','Select');
	public static $TimeZoneType                = array('AbuDhabiMuscat','Adelaide','Alaska','AlmatyNovosibirsk','AmsterdamBerlinBernRomeStockholmVienna','Arizona','AstanaDhaka','AthensBuckarestIstanbul','AtlanticTimeCanada','AucklandWellington','Azores','Baghdad','BakuTbilisiYerevan','BangkokHanoiJakarta','BeijingChongqingHongKongUrumqi','BelgradeBratislavaBudapestLjubljanaPrague','BogotaLimaQuito','Brasilia','Brisbane','BrusselsCopenhagenMadridParis','Bucharest','BuenosAiresGeorgetown','Cairo','CanberraMelbourneSydney','CapeVerdeIsland','CaracasLaPaz','CasablancaMonrovia','CentralAmerica','CentralTimeUSCanada','ChennaiKolkataMumbaiNewDelhi','ChihuahuaLaPazMazatlan','Darwin','EasternTimeUSCanada','Ekaterinburg','FijiKamchatkaMarshallIsland','Greenland','GreenwichMeanTimeDublinEdinburghLisbonLondon','GuadalajaraMexicoCityMonterrey','GuamPortMoresby','HararePretoria','Hawaii','HelsinkiKyivRigaSofiaTallinnVilnius','Hobart','IndianaEast','InternationalDatelineWest','IrkutskUlaanBataar','IslamabadKarachiTashkent','Jerusalem','Kabul','Kathmandu','Krasnoyarsk','KualaLumpurSingapore','KuwaitRiyadh','MagadanSolomonIslandNewCaledonia','MidAtlantic','MidwayIslandAndSamoa','MoscowStPetersburgVolgograd','MountainTimeUSCanada','Nairobi','Newfoundland','Nukualofa','OsakaSapporoTokyo','PacificTimeUSCanadaTijuana','Perth','Rangoon','Santiago','SarajevoSkopjeWarsawZagreb','Saskatchewan','Seoul','SriJayawardenepura','Taipei','Tehran','Vladivostok','WestCentralAfrica','Yakutsk');
	public static $UserLifeCycleStatus         = array('New','Active','Inactive','Deleted');
	public static $UserRole                    = array('AdvertiserCampaignManager','SuperAdmin','ClientViewer','ClientManager','PublisherAdmin','PublisherAccountManager','PublisherReportUser','PublisherListManager','PublisherAdViewer','ClientAdmin');
}

?>